baseURL = "https://crstian19.github.io/"
title = "Crstian's blog"
googleAnalytics = "UA-138916983-1"
theme = "github-style"
copyright = "Crstian.me © 2019. Powered by  <a href=\"https://gohugo.io/\">HUGO</a>"

[params]
  author = "Cristian Gutierrez"
  # description = "example"
  github = "Crstian19"
  linkedin = "cristian-gutierrez-lopez/"
  # twitter = "example"
  gitlab = "user profile url"
  # mastodon = "user profile url"
  email = "cristian@crstian.me"
  utterances = "example/example.github.io"
  avatar = "https://raw.githubusercontent.com/parnurzeal/gorequest/gh-pages/images/Gopher_GoRequest.jpg"
  url = "https://crstian.me"
  urlb = "https://blog.crstian.me"
  urlc = "https://server.crstian.me"
  urlshell ="https://shell.crstian.me"
  keywords = "blog, google analytics, crstian, traefik, pixel, experience, español"
